version: '3'

services:
  wordpress:
    image: wordpress:6.1.1
    env_file: .env
    restart: ${RESTART}
    environment:
      LETSENCRYPT_HOST: ${MYHOST}
      VIRTUAL_HOST: ${MYHOST}
      VIRTUAL_PATH: /${DOMAIN_PATH}/
      VIRTUAL_DEST: /${DOMAIN_PATH}/
      VIRTUAL_PORT: 80
      WORDPRESS_EXTRA_CONFIG: |
        define( 'WP_SITEURL', '${DOMAIN_PRE}://${MYHOST}/${DOMAIN_PATH}');
        define( 'WP_HOME', '${DOMAIN_PRE}://${MYHOST}/${DOMAIN_PATH}');

    working_dir: /var/www/html/${DOMAIN_PATH}
    volumes:
      - ./data/wordpress:/var/www/html/${DOMAIN_PATH}:rw
      - ./plugin-wp-sqlite-db/db.php:/var/www/html/${DOMAIN_PATH}/wp-content/db.php:ro
      - ./data/db.sqlite:/var/www/html/${DOMAIN_PATH}/wp-content/.ht.sqlite
    networks:
      - topDomainProxy

networks:
  topDomainProxy:
    external: true
